/* =========================================================================
 * /api/account/reorder  (REWRITTEN for real schema)
 *
 * POST { sourceOrderId } → clones a past order into a new draft order
 * in the same `orders` table. The new row:
 *   - inherits customer_id, items, subtotal, tax, total, notes,
 *     program_id (if set)
 *   - gets a fresh order_number generated by the existing CRM sequence
 *     (or a synthesized REO-<short-uuid> if no sequence is wired)
 *   - status='new', paid_status='unpaid', paid=false, NO Stripe sessions
 *
 * Ownership is enforced via customer_id → customers.user_id = auth.uid().
 *
 * Response: { order: { id, order_number, trackingUrl } }
 * ========================================================================= */

const { requireUser, setCorsHeaders, readJsonBody } = require('../_lib/auth');
const { adminClient } = require('../_lib/supabase');
const crypto = require('crypto');

// Columns we carry over from the source order to the clone. Deliberately
// NOT carrying: paid, paid_status, stripe_invoice_id, deposit_*,
// balance_*, invoice_opened_at, status, order_number — all of those
// are fresh-order state and would mislead the CRM if copied.
const CARRY = [
  'customer_id', 'lead_id', 'items',
  'subtotal', 'tax', 'total',
  'notes', 'deadline'
];

function freshOrderNumber() {
  // Fallback when there's no SQL sequence wired into the orders table.
  // REO- prefix so the CRM ops team can immediately recognise these as
  // reorders. 6-char alphanum suffix → 36^6 = 2.2B combinations.
  const suffix = crypto.randomBytes(4).toString('base64')
    .replace(/[^A-Za-z0-9]/g, '').slice(0, 6).toUpperCase();
  return `REO-${suffix}`;
}

module.exports = async function handler(req, res) {
  setCorsHeaders(res);
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')    return res.status(405).json({ error: 'method not allowed' });

  let user;
  try { ({ user } = await requireUser(req)); }
  catch (e) { return res.status(e.status || 500).json(e.body || { error: 'auth failed' }); }

  let body;
  try { body = await readJsonBody(req); }
  catch (e) { return res.status(400).json({ error: e.message }); }

  if (!body.sourceOrderId) return res.status(400).json({ error: 'sourceOrderId required' });

  const supabase = adminClient();

  // 1. Get the caller's customer_id(s) so we can enforce ownership.
  const { data: cust, error: cErr } = await supabase
    .from('customers').select('id').eq('user_id', user.id);
  if (cErr) return res.status(500).json({ error: cErr.message });
  const customerIds = (cust || []).map((c) => c.id);
  if (!customerIds.length) {
    return res.status(404).json({ error: 'no customer record on file' });
  }

  // 2. Fetch the source order, scoped to the caller's customer rows.
  const selectCols = ['id', 'customer_id', 'paid_status', 'balance_paid_at', 'paid', ...CARRY].join(', ');
  const { data: src, error: srcErr } = await supabase
    .from('orders')
    .select(selectCols)
    .eq('id', body.sourceOrderId)
    .in('customer_id', customerIds)
    .maybeSingle();
  if (srcErr) return res.status(500).json({ error: srcErr.message });
  if (!src)   return res.status(404).json({ error: 'source order not found' });

  // Only completed orders can be reordered.
  const wasPaid = src.paid === true
    || (src.paid_status && /^(paid|refunded)$/i.test(src.paid_status))
    || src.balance_paid_at != null;
  if (!wasPaid) {
    return res.status(409).json({ error: 'only completed orders can be reordered' });
  }

  // 3. Insert the clone.
  const insertRow = {
    order_number: freshOrderNumber(),
    status:       'new',
    paid_status:  'unpaid',
    paid:         false
  };
  for (const col of CARRY) insertRow[col] = src[col];

  const { data: inserted, error: insErr } = await supabase
    .from('orders')
    .insert(insertRow)
    .select('id, order_number')
    .single();
  if (insErr) return res.status(500).json({ error: insErr.message });

  const trackingUrl = `/order/${encodeURIComponent(inserted.order_number)}`;
  return res.status(201).json({
    order: {
      id:           inserted.id,
      orderNumber:  inserted.order_number,
      trackingUrl
    }
  });
};
